### ISSUE TITLE
RMSE Calculation problems

### ISSUE THREAD

**Issue by Lunarli** [LLerDagu/RUL-FFVE#1]
Hi,thanks for sharing the elegant code,The code is very easy to reproduce, and I also get results similar to those in your paper.

But I find a Calculation problem In line 290 of your code
 you used **test_ rmse +=rmse_ Loss. item() / len (test_loader)** to calculate test RMSE.
I wonder maybe this calculation method  using     **batch average RMSE instead of overall RMSE**.     **This calculation will result in a smaller RMSE result**, and the true RMSE should be the root mean square error of all predicted results.

Below are my reproduction results and reproduction code charts（**FFVE-RMSE used the corrected RMSE calculation method**）
![image](https://github.com/LLerDagu/RUL-FFVE/assets/49749330/2edb4e5b-c74e-4143-bceb-895202905e3e)
![image](https://github.com/LLerDagu/RUL-FFVE/assets/49749330/e6630f53-b4ba-44f4-afae-8898dbb57c14)

**Comment by LLerDagu** [comment]
Thank you for your keen interest in our project and for bringing up the associated concerns.

The code segment in question originates from others earlier open-source endeavors. Following your discovery, we conducted a thorough review and determined that this computation method does not impact the training and validation of our method. **However, we have indeed identified the issue of using batch average RMSE instead of overall RMSE, specifically in the C-MAPSS turbofan engine dataset's test set.**

Furthermore, it's worth noting that the conclusions drawn from experiments on the C-MAPSS turbofan engine dataset and ablation studies remain unaffected. Additionally, the experiments conducted on the NASA lithium-ion battery dataset are based on a different open-source framework, ensuring that this issue does not impact the results of our work on the NASA lithium-ion battery dataset.

While we cannot pinpoint when this issue originated in others previous work, we are committed to actively addressing and rectifying it. **Following this, we will promptly update and correct the relevant work on our GitHub repository.**

Should you be willing, we would like to express our gratitude by acknowledging your name on our project's main page.

Once again, we sincerely thank you for your valuable contributions to our project!

---------------------------------------------------------------------------
Here is the code that we will update later:
![1](https://github.com/LLerDagu/RUL-FFVE/assets/51023462/9b0994ac-d97f-4a7e-a48f-8dfc46bea2da)
![2](https://github.com/LLerDagu/RUL-FFVE/assets/51023462/0431d36d-e02b-4b2c-861f-01f95154f6bd)

**Comment by Lunarli** [comment]
**Appreciation for your reply and looking forward to further test results**

Thank you for your swift response and for addressing the issues I raised in my previous correspondence.

It is reassuring to know that, following your thorough review, the identified computation method does not impact the training and validation of your method, a conclusion with which I concur. However, I do have concerns about **obtaining lower RMSE results when using the batch average RMSE as opposed to the overall RMSE on the test set of the C-MAPSS turbofan engine dataset.（As shown in my previous  image)** 
![image](https://github.com/LLerDagu/RUL-FFVE/assets/49749330/92630890-69f6-4007-8533-9e94bf18bda7)

 
I am keenly anticipating the enhancements you will make. **I look forward to examining the revised code and observing the test results on the C-MAPSS dataset post-adjustment.** 

Separately, I would like to express once again my admiration for the **elegance and readability** of your source code. Your paper is **comprehensive and well-articulated**, making it one of the most impressive I have recently encountered. Thank you for contributing such a remarkable open-source project to the community.

 Best regards

**Comment by LLerDagu** [comment]
Thank you for your affirmation. It is the best praise for our work!

**Currently, we have already updated the erroneous code.** Unfortunately, our original computing resources are temporarily unavailable, preventing us from immediately recalculating the RMSE. Perhaps we will need to use new equipment for the recalculation in the future. **Consequently, we plan to update the performance metrics on the C-MAPSS turbofan engine dataset at a later time.**

Additionally, correcting errors in the paper is a challenging task. We are actively considering how to inform others of the correct calculation results as soon as possible to prevent the dissemination of inaccurate findings. Your assistance in sharing the correct results with others is highly welcome.

**Comment by Lunarli** [comment]
Okay, Got it

**Comment by LLerDagu** [comment]
Hi, we have promptly updated the data affected by the mentioned issue, and you can find all the errata [here](https://github.com/LLerDagu/RUL-FFVE/blob/main/Benchmark.md)!

It's worth noting that, due to the inability to use the equipment mentioned in the paper, we used a new device to compute the results. Therefore, there may be some variations in SCORE compared to the original results (SCORE will remain unchanged if the same equipment is used). If you need to make performance comparisons, you can refer to these new results.

Furthermore, from the experimental results, all the conclusions mentioned in the paper still hold true, so there is no need to worry about any textual errors in the paper.

Finally, we apologize for the error in our code and appreciate your valuable contributions!
